In [14]:
# Question 11

# Objective Function: 12a + 16b + 21c = P
# 3a + 7b + 5c ≤ 4500
# 9a + 6b + 13c ≤ 8240
# A, B, C ≥ 0

from scipy.optimize import linprog 

i = [-12, -16, -21]
lhs = [[3,7,5],[9,6,13]]
rhs = [4500,8240]

x1_bound = (0,None)
x2_bound = (0,None)
x3_bound = (0,None)

solution = linprog(c=i, A_ub=lhs, b_ub=rhs, bounds = (x1_bound,x2_bound,x3_bound),method='simplex')
print(solution.fun)
print(solution.x)

-15099.672131147541
[  0.         283.60655738 502.95081967]


In [20]:
# Question 12

# Objective Function: 180x1 + 110x2 = i
# 4x1 + 2x2 ≤ 26
# 3x1 + 3x1 ≤ 27

i = [-180,-110]
lhs = [[4,2],[3,3]]
rhs = [26,27]

x1_bound = (0,None)
x2_bound = (0,None)
solution = linprog(c = i, A_ub = lhs, b_ub = rhs, bounds = (x1_bound,x2_bound), method = 'simplex')
print(solution.fun)
print(solution.x)

-1270.0
[4. 5.]


In [26]:
# Question 13

# Atlanta needs at 14 million gallons of water per day
# Water can come from either reservoir of pipeline
# Local reservoir has a maximum yield of 18 million gallos
# Pipeline has a maximum yield of 13 million gallons
# Pipeline is required to supply a minimum of 7 million gallons/day
# Reservoir costs $415 per M gallons
# Pipeline costs $465 per M galoons

# Minimize costs

# Objective Function: c = 415r + 465p
# r + p ≥ 14
# r ≤ 18
# p ≥ 7
# p ≤ 13

i = [415,465]
lhs = [[-1,-1],[1,0],[0,-1],[0,1]]
rhs = [-14,18,-7,13]
r_bound = (0,None)
p_bound = (0,None)
solution = linprog(c=i, A_ub=lhs, b_ub=rhs, bounds = (r_bound,p_bound), method = 'simplex')
print(solution.fun)
print(solution.x)

6160.0
[7. 7.]


In [41]:
# Question 14

# Diet must contain:
# 1720 mg Vitamin C
# 3240 mg Calcium
# 3460 calories

# Dairy-based: 20 mg Vitamin C, 30 mg Calcium, 50 calories, per oz
# Dairy-based costs $0.33 / oz

# Vegan: 20 mg Vitamin C, 50 mg Calcium, 30 calories, per oz
# Vegan costs $0.22 / oz

# Minimize costs

# Objective Function c = 0.21d + 0.24v
# 40d + 20v ≥ 2000
# 20d + 50v ≥ 2800
# 50d + 30v ≥ 3500

i = [0.29,0.30]
lhs = [[-20,-30],[-40,-20],[-50,-40]]
rhs = [-2010,-2460,-3660]
x1_bound = (0,None)
x2_bound = (0,None)
solution = linprog(c=i, A_ub=lhs, b_ub=rhs, bounds=(x1_bound,x2_bound), method='simplex')
print(solution.fun)
print(solution.x)

23.88
[42. 39.]


In [49]:
# Question 15

# Lawn seed mix contains:
# bg, r, B
# 12, 15, 5 (cost)
# bg ≥ 0.20, B ≤ (2/3)(r)
# bg + r + B ≥ 6000

# 15bg + 16r + 5 = c
# bg + r + B ≥ 8000
# bg ≥ 20%
# r ≤ 48%
# B ≤ 32%

i = [-0.15,-0.16,-0.05]
lhs = [[-1,-1,-1],[-1,0,0],[0,1,0],[0,0,1]]
rhs = [-8000,-1600,3840,2560]
x1_bound = (0,None)
x2_bound = (0,None)
x3_bound = (0,None)
solution = linprog(c=i, A_ub=lhs, b_ub=rhs, bounds=(x1_bound,x2_bound,x3_bound), method='simplex')
print(solution.fun)
print(solution.x)

-982.4
[1600. 3840. 2560.]


In [39]:
# Dual calculation

import matplotlib.pyplot
from matplotlib.pyplot import *
import numpy
from numpy import *

lhs = [[20,20],[30,50],[50,30]]
lhs = matrix(lhs)
lhs = transpose(lhs)
print(lhs)


[[20 30 50]
 [20 50 30]]
