In [1]:
import numpy as np

#### NumPy Vectors

In [10]:
sample_vector = np.array([1,2,3])
sample_vector

array([1, 2, 3])

In [16]:
sample_vector_two = np.array([4,5,6])
sample_vector_two

array([4, 5, 6])

#### NumPy Matrices

In [12]:
sample_matrix = np.matrix([[1,2,3],[4,5,6]])
sample_matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [170]:
sample_matrix.shape

(2, 3)

In [64]:
sample_matrix_two = np.matrix([[1,2],[3,4],[5,6]])
sample_matrix_two

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [169]:
sample_matrix_two.shape

(3, 2)

#### Vector Dot Product

In [92]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1         
    assert len(y.shape) == 1         
    assert x.shape[0] == y.shape[0]
    z = 0. 
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [19]:
naive_vector_dot(sample_vector,sample_vector_two)

32

#### Matrix Vector Dot Product

In [20]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2              
    assert len(y.shape) == 1              
    assert x.shape[1] == y.shape[0]       
    z = np.zeros(x.shape[0])              
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [21]:
naive_matrix_vector_dot(sample_matrix,sample_vector)

array([14., 32.])

#### Matrix Dot Product

In [197]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2                  
    assert len(y.shape) == 2                  
    assert x.shape[1] == y.shape[0]           
    z = np.zeros((x.shape[0], y.shape[1]))   
    for i in range(x.shape[0]):               
        for j in range(y.shape[1]):           
            row_x = np.array(x[i, :]).flatten()
            column_y = np.array(y[:, j]).flatten()
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [198]:
naive_matrix_dot(sample_matrix,sample_matrix_two)

array([[22., 28.],
       [49., 64.]])